exp_id: parametrization_minimalNet_nnParam_fastDynamics_T5_nrollout10_nonlocal
datadir: /gpfs/work/nonnenma/data/emulators/L96/
res_dir: /gpfs/work/nonnenma/results/emulators/L96/
K: 36
J: 10
T: 5.0
dt: 0.01
l96_F: 10.
l96_h: 1.
l96_b: 10.
l96_c: 10.
train_frac: 0.8
validation_frac: 0.2
spin_up_time: 5.
model_exp_id: 42
model_forwarder: rk4_default
loss_fun: mse
batch_size: 32
lr: 1e-3
lr_min: 1e-6
lr_decay: 0.1
weight_decay: 0.
max_lr_patience: 10
max_patience: 20
eval_every: 50
max_epochs: 5000
parametrization: nn
n_hiddens: [8, 8]
kernel_size: 3
offset: [1,2,3,4,5,6,7,8,9,10]
